# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
  - "3.4"

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=1.11
      - python: "3.5"
        env: DJANGO=1.8
      - python: "3.5"
        env: DJANGO=1.10
      - python: "3.5"
        env: DJANGO=1.11
      - python: "3.3"
        env: DJANGO=1.8

services:
  - memcached

install: pip install tox tox-travis codecov

script: tox

after_success: codecov
