# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=1.11
      - python: "3.3"
        env: DJANGO=1.8
    exclude:
      - python: "3.5"
        env: DJANGO=1.7
      - python: "3.5"
        env: DJANGO=1.6
      - python: "3.5"
        env: DJANGO=1.5

services:
  - memcached

install: pip install tox tox-travis codecov

script: tox

after_success: codecov
